### ISSUE TITLE
Works in Big Sur Beta 1

### ISSUE THREAD

**Issue by kvndrsslr** [tsujp/custom-macos-gui#2]
![image](https://user-images.githubusercontent.com/46481738/85526067-f9323700-b609-11ea-9517-ec32df6efa63.png)

Reproduce:

- new aqua appearance is inside the same folder, but currently in subfolder `.instrumentedappearances`
- copy over to Catalina drive
- edit in ThemeEngine on Cataline drive
- copy back to Big Sur

This issue is a placeholder and will be updated for the duration of the beta.
On Big Sur release, I will create a PR for this.

**Comment by tsujp** [comment]
Sounds good, keep me updated and once Big Sur is out of beta in the autumn (I think it is) I can use my machine to give it a test and merge.

**Comment by tsujp** [comment]
Installing on my machine tonight, will be updating and trying this out including all possible themes in preparation for Big Sur's Autumn release.

**Comment by tsujp** [comment]
In order to support N combinations of options I am creating a little framework and custom `.car` archive extractor/creator to achieve this. Stay tuned.
