### ISSUE TITLE
Stutter on Catalina

### ISSUE THREAD

**Issue by drewauff** [tsujp/custom-macos-gui#4]
Visually its perfect..

when dragging windows around it is slow and it stutters .. not smooth at all.

Activity Monitor is the most stuttery and laggy when dragging/moveing the app window.

hopefully you can fix this.

**Comment by tsujp** [comment]
This is with just these changes right? I can have a look at putting my machine onto Catalina this weekend and testing things out there.

**Comment by tsujp** [comment]
@drewauff I've heard numerous reports that Catalina is slow and glitchy in-general; a few questions:

(1) have you restarted your machine and verified this occurs after a restart?
(2) what about turning wifi on/off and it continuing?
(3) in Activity Monitor is `accountsd` using high CPU or other resources?
(4) were you using Catalina extensively before patching your appearance? If so, did this occur immediately after patching?
(5) were you on Mojave previously? If yes, what was performance like with or without this patch?

**Comment by drewauff** [comment]
1) yes
2) doubt thats it, but did it anyway
3) no not cpu usage but 2gb+ memory..I have 16gb
4) yes, yes.
5) was on Mojave. only patched on Catalina. Performance is great on Mojave and Catalina.

The stutter is bad and only on Activity monitor.

Even after running purge and flushdns still stutters.

note: Activity Monitor works perfectly, just cant move the app around desktop without massive stutter.

**Comment by tsujp** [comment]
Roger thank you for answering those. Yeah (2) was definitely a hail mary from some random comment on a Catalina thread I saw.

This will take some time to check -- I guess for now if everything but Activity Monitor works that'll have to be the state of things until I can determine why _just_ Activity Monitor behaves this way.

**Comment by drewauff** [comment]
dude just realised your a fellow Aussie haha..I from the now covid free sate of Vic.

**Comment by drewauff** [comment]
hey I want to upgrade to Big Sur, have you got this fully working on it yet?

**Comment by tsujp** [comment]
@drewauff hey I've been busy with work; will check after work today (slipped my mind) -- stay tuned.

**Comment by tsujp** [comment]
@drewauff got round to this finally and it's fine for me on 11.2, be sure to backup the `.car` files before attempting so you can easily undo. Let me know how you go please :)

**Comment by tsujp** [comment]
@drewauff I'm closing this as I'm unable to verify and it's been a while but please comment back if this resumes, same for anyone who happens to be reading this.
