### ISSUE TITLE
Where do WindowFrame_WindowShapeEdges need to be copied to?

### ISSUE THREAD

**Issue by LeeBinder** [tsujp/custom-macos-gui#6]
Hi tsujp,

where to copy the .png graphics files in WindowFrame_WindowShapeEdges/edited?

**Comment by tsujp** [comment]
Hey the edited `.png` files at that path are the sources for the edited `.car` files I provide -- you don't need to copy those unless you want to build the `.car` files yourself. Instead you can copy the `.car` file to `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/` as mentioned in the readme.

**Comment by LeeBinder** [comment]
Allright gotcha, Jordan. I thought I had replied before, but not seeing my answer I guess I was suffering some overload back then. I now understand. Just bummer this does not work for Big Sur because these hyper-rounded corners are simply way over-the-top.
