### ISSUE TITLE
osx 12 can't write in to /system folder

### ISSUE THREAD

**Issue by ghost** [tsujp/custom-macos-gui#9]
Hi, I have tried to replace the Aqua.car file, but unfortunately even after disable SIP the file system seems still read-only.

```
=> csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled
	Boot-arg Restrictions: enabled
	Kernel Integrity Protections: enabled
	Authenticated Root Requirement: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

```
=> sudo mv ~/Downloads/customise_macos-0.1.0/appearance/Aqua/Aqua.car .
override rw-r--r--  root/wheel for ./Aqua.car? (y/n [n]) y
mv: fastcopy: open() failed (to): ./Aqua.car: Read-only file system
```

```
❯ sudo mount -uw /
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
```

**Comment by ghost** [comment]
I searched google for a while, it seems after osx 11 the mac had disabled SIP backdoor so simply` csrutil disable `will not work, had you checked this on M1 chip? I'm on M1 pro platform with osx 12.4

**Comment by ghost** [comment]
in particular, through this [answer](https://superuser.com/questions/1681655/how-to-change-a-read-only-file-system-to-a-writable-file-system-on-mac-monterey), it seems the system file is totally unchangeable.

Please help to provide more info about how to apply those car files.

**Comment by ghost** [comment]
@tsujp please help to check this issue

**Comment by tsujp** [comment]
Sorry I don't know why I missed this notification... I can check this weekend I have some prior obligations this week.

**Comment by tsujp** [comment]
Between now and then it might be worth giving it a shot quickly with _all_ of SIP disabled and not just the filesystem and debugging; just to see.

**Comment by tsujp** [comment]
@akanes0ra it appears that for Big Sur onwards it is more work to replace `.car` files. See instructions here: https://github.com/jslegendre/ThemeEngine#themeengine

I'm working on a thing which does not require replacing files on-disk which I alluded to elsewhere but it's a lot of work so don't expect it soon. For now your only choice might be the instructions above.

**Comment by ghost** [comment]
> 

Ye I can tell it's a lot work to do for replacing system file right now. I will leave it since I have many priorities now...
